# include <iostream.h>
# include <conio.h>
class father
{
int age;
public;
void getfather()
{
cout<<"enter fathers age";
cin>>age;
}
class mother
int mage;
public;
void getmother()
{
cout<<"enter mothers age ";
cin>>mage;
}
class son.public father,public mother
char name;
public
void getname()
{
cout<<"enter your name ";
cin>>name;
}
void main()
son p;
p.getfather();
p.getmother();
p.getname();
getch();
};



