#include"my.h"
class student
{ char Name[50];
int rollno;
public: void getdata1(void)
{ cout<<" Enter the name of the student";
gets(name);
cout<<"\n enter the roll no. of the student";
cin>>rollno;
}
void putdata1(void)
{cout<<"\n the name of the student is=";
puts(name);
cout<<"\n the roll no is="<<rollno;
}                                                                            ffffffddxcv
}






void main()
{
clrscr();

getch();
}