#include<iostream.h>
#include<conio.h>
main()
{
clrscr();
float p,mp,dis,pay;
cout<<"\n\n price of item=";
cin>>p;
cout<<"\n\n enter mode of payment=  ";
cout<<"\n\n 1.cash 2.cheque 3.card  ";
cin>>mp;
if(mp==1)
{
 cout<<"\n\n you have choose cash payment method ";
 dis=p*0.07;
 pay=(p-dis);
 cout<<"\n\n your discount in(rs)==     "<<dis;
 cout<<"\n\n your bill amount is  "<<pay;
}
else if(mp==2)
{
 cout<<"\n\n you have choose cheque payment method ";
 dis=p*0.05;
 pay
getch();
}

