# include <iostream.h>
void main()
{
int n,d;
cout<<"enter the number";
cin>> n;
d=n%10;
switch(d);
{
case1:
{
cout<<"last digit is one";
}
break;
case2:
{
cout<<"last digit is two";
}
break;
case3:
{
cout<<"last digit is three";
}
break;
case4:
{
cout<<"last digit is four";
}
break;
case5:
{
cout<<"last digit is five";
}
break;
case6:
{
cout<<"last digit is six";
}
break;
case7:
{
cout<<"last digit is seven";
}
break;
case8:
{
cout<<"last digit is eight";
}
break;
case9:
{
cout<<"last digit is nine";
}
break;
case0:
{
cout<<"last digit is zero";
}
break;
default:
{
cout<<"invalid input";
}
}
}


